version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: meraki_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: meraki_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
